### ISSUE TITLE
Bug if I use Cyrillic

### ISSUE THREAD

**Issue by BerndDemian** [RolfBremer/typst-index#2]
Thanks for your index packet. But when I use Cyrillic, I get an error.
Example:

#index ("Skorospelka") // this is ok
#index("Скороспелка") // error

error: string index 1 is not a character boundary
   ┌─ ../Basics/index.typ:76:30
   │
76 │         #let firstCharacter = sk.slice(0,1)
   │                               ^^^^^^^^^^^^^
re 

Thanks Bernd

**Comment by RolfBremer** [comment]
Thanks, Bernd!
We will have a look into it.

**Comment by RolfBremer** [comment]
Ok, found and fixed it.
It was a problem with slice(), which fails on graphemes consisting of more than one byte. 
I changed it to first(), what does what we wanted anyway.

Thank you for the feedback and sample. Let me know if it works for you now.

Rolf

**Comment by BerndDemian** [comment]
Thanks,
ich denke, das Resultat ist nicht das Erwartete. Irgendwie sind die Einträge doppelt, einmal mit "" und einmal ohne.
Ich habe dein sample-index.typ benutzt. Bei mir sieht es genau so aus.
[sample-usage.pdf](https://github.com/RolfBremer/typst-index/files/11487562/sample-usage.pdf)

Danke!

**Comment by BerndDemian** [comment]
Hallo,
without line 76: #repr(sk) it seems ok, for me.
Tanks
